default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit  # https://beta.ruff.rs/docs/usage/#github-action
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.3
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Cruft update rejection files (`.rej`); review them and then remove them.
        language: fail
        files: "\\.rej$"

ci:  # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: monthly