name: pam
channels:
  - conda-forge
  - default
dependencies:
    - click >= 8.1, < 9
    - gdal < 3.6
    - geopandas >= 0.13, < 0.14
    - ipykernel >= 5.2, < 6
    - lxml >= 4.6, < 5
    - matplotlib >= 3.2, < 4
    - pandas >= 1.3, < 2
    - pip ~= 23.1
    - pip:
      - s2sphere < 0.3
    - plotly >= 4.10, < 5
    - prettytable >= 3.3, < 4
    - python >=3.7, <3.12
    - python-Levenshtein >= 0.21, < 0.22
    - rich >= 12.5, < 13
    - Rtree >= 0.9, < 1
    - scikit-learn >= 1.2, < 2
    - shapely > 2.0, < 3
    - xlrd >= 2.0, < 3
    # dev
    - nbmake ~= 1.3
    - pre-commit ~= 3.3
    - pytest ~= 7.3
    - pytest-cov ~= 4.1
    - pytest-mock ~= 3.10
    - pytest-timeout ~= 2.1
    - pytest-xdist ~= 3.3
    # docs
    - colorama
    - jupyter < 2
    - jupyter_contrib_nbextensions < 0.6
    - mike ~= 1.1
    - mkdocs ~= 1.4
    - mkdocs-click ~= 0.6.0
    - mkdocs-jupyter ~= 0.24.1
    - mkdocstrings-python ~= 1.1
    - tabulate < 1
