name: pam
channels:
  - conda-forge
  - default
dependencies:
    - click < 9
    - gdal < 3.6
    - geopandas >= 0.13, < 0.14
    - ipykernel < 7
    - lxml < 5
    - matplotlib >= 3, < 4
    - numpy >= 1, < 2
    - pandas >= 1.5, < 3
    - pip >= 23, < 24
    - pip:
      - s2sphere < 0.3
    - plotly >= 4, < 6
    - prettytable >= 3, < 4
    - python >= 3.9, < 3.12
    - python-Levenshtein >= 0.21, < 0.22
    - rich >= 12, < 14
    - Rtree >= 1, < 2
    - scikit-learn >= 1.2, < 2
    - shapely >= 1, < 3
    - xlrd >= 2, < 3
    # dev
    - nbmake < 2
    - pre-commit < 4
    - pytest < 8
    - pytest-cov < 5
    - pytest-mock < 4
    - pytest-timeout < 3
    - pytest-xdist  < 4
    # docs
    - jupyter < 2
    - mike < 2
    - mkdocs < 2
    - mkdocs-click < 0.7
    - mkdocs-jupyter < 0.25
    - mkdocstrings-python < 2
