name: pam
channels:
  - conda-forge
  - default
dependencies:
    - python >=3.7, <3.12
    - click >= 8.1, < 9
    - gdal < 3.6
    - geopandas >= 0.13, < 0.14
    - ipykernel >= 5.2, < 6
    - lxml >= 4.6, < 5
    - matplotlib >= 3.2, < 4
    - pandas >= 1.3, < 2
    - plotly >= 4.10, < 5
    - prettytable >= 3.3, < 4
    - rich >= 12.5, < 13
    - Rtree >= 0.9, < 1
    - xlrd >= 2.0, < 3
    - scikit-learn >= 1.2, < 2
    - python-Levenshtein >= 0.21, < 0.22
    - shapely > 2.0, < 3
    - colorama
    - jupyter_contrib_nbextensions < 0.6
    - jupyter < 2
    - tabulate < 1
    - memory_profiler
    - pytest-cov
    - pytest-mock
    - pytest-xdist
    - pytest
    - pip
    - pip:
      - s2sphere < 0.3
