site_name: Population Activity Modeller (PAM)
nav:
  - Home: index.md
  - Installation: installation.md
  - Reading data: read_data.md
  - Activity plans: activity_plans.md
  - Modelling the impact of policies on populations: modelling_policy_impact.md
  - Examples:
    - examples/01_basics.ipynb
    - examples/02a_tabular_read_write.ipynb
    - examples/02b_matsim_read_write.ipynb
    - examples/03_read_modify_write.ipynb
    - examples/04_point_sampling.ipynb
    - examples/05_activity_plots.ipynb
    - examples/05_policies_walk_through.ipynb
    - examples/06_travel_plots.ipynb
    - examples/07_travel_survey_to_matsim.ipynb
    - examples/08_toy_matsim_population.ipynb
    - examples/09_advanced_policies.ipynb
    - examples/10_advanced_spatial_sampling.ipynb
    - examples/11_Advanced_Plan_Rescheduling.ipynb
    - examples/12_Advanced_Adding_Vehicles.ipynb
    - examples/13_Advanced_Freight_Synthesis.ipynb
    - examples/14_Advanced_Plan_Cropping.ipynb
    - examples/15_advanced_choice_modelling.ipynb
    - examples/16_advanced_matsim_warmstarting.ipynb
  - Contributing:
    - contributing/index.md
    - Coding contributions: contributing/coding.md
    - Non-coding contributions: contributing/non_coding.md
  - Changelog: CHANGELOG.md
  - Reference:
    - Command line interface: api/cli.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
  logo: resources/logos/small.png
  favicon: resources/logos/mini.png
repo_url: https://github.com/arup-group/pam/
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      permalink: "#"
      toc_depth: 3
hooks:
  - docs/static/hooks.py
plugins:
  - autorefs
  - generate-api:
      package_dir: "pam"
      api_dir: "api"
      skip:
          - pam/cli.py
          - pam/variables.py
  - mkdocs-jupyter:
      include: ["examples/*.ipynb"]
      allow_errors: false
      kernel_name: pam
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: spacy
            show_bases: true
            filters:
              - "!^_"
            merge_init_into_class: true
            show_if_no_docstring: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: false
          import:
            - https://docs.python.org/3/objects.inv
            - https://shapely.readthedocs.io/en/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://geopandas.org/en/stable/objects.inv
  - search
watch:
  - pam
extra_css:
  - static/extras.css
extra:
  version:
    provider: mike
