site_name: Population Activity Modeller (PAM)
nav:
  - Home: index.md
  - Installation: installation.md
  - Reading data: read_data.md
  - Activity plans: activity_plans.md
  - Modelling the impact of policies on populations: modelling_policy_impact.md
  - Examples:
    - PAM Getting Started: examples/01_PAM_Getting_Started.ipynb
    - Population Basics: examples/02_Population_Basics.ipynb
    - Example Generate Random Population: examples/03_Example_Generate_Random_Population.ipynb
    - Example Ingest NTS Diaries: examples/04_Example_Ingest_NTS_Diaries.ipynb
    - PAM Policies Walk Through: examples/05_PAM_Policies_Walk_Through.ipynb
    - PAM Complex Policies: examples/06_PAM_Complex_Policies.ipynb
    - PAM Point Sampling: examples/07_PAM_Point_Sampling.ipynb
    - PAM Population Activity Plots: examples/08_PAM_Population_Activity_Plots.ipynb
    - Travel Plots: examples/09_Travel_Plots.ipynb
    - Advanced Spatial-Sampling Demo: examples/10_Advanced_Spatial-Sampling_Demo.ipynb
    - Advanced Plan Rescheduling: examples/11_Advanced_Plan_Rescheduling.ipynb
    - Advanced Adding Vehicles: examples/12_Advanced_Adding_Vehicles.ipynb
    - Advanced Freight Synthesis: examples/13_Advanced_Freight_Synthesis.ipynb
    - Advanced Plan Cropping: examples/14_Advanced_Plan_Cropping.ipynb
    - Advanced Choice: examples/15_Advanced_Choice.ipynb
  - Contributing: 
    - contributing/index.md
    - Coding contributions: contributing/coding.md
    - Non-coding contributions: contributing/non_coding.md
  - Changelog: CHANGELOG.md
  - Reference: 
    - Command line interface: api/cli.md
theme: 
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
repo_url: https://github.com/arup-group/pam/
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      permalink: "#"
      toc_depth: 3
hooks:
  - docs/static/hooks.py
plugins:
  - autorefs
  - generate-api:
      package_dir: "pam"
      api_dir: "api"
      skip:
          - pam/cli.py
          - pam/variables.py
  - mkdocs-jupyter:
      include: ["examples/*.ipynb"]
      allow_errors: false
      kernel_name: pam
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true
            filters:
              - "!^_"
            merge_init_into_class: true
            show_if_no_docstring: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_toc_entry: false
  - search
watch: 
  - pam
extra_css:
  - static/extras.css
extra:
  version:
    provider: mike
 