name: Minimal CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml

jobs:
  test:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@v1.1.0
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: pam
      lint: false
      upload_to_codecov: false

  aws-upload:
    needs: test
    if: needs.test.result == 'success'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/aws-upload.yml@v1.1.1
    secrets: inherit
