name: Daily CI Build

on:
  schedule:
    - cron: '23 14 * * 1-5'
    
jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@main
    with:
      os: ubuntu-latest
      py3version: "11"
      notebook_kernel: pam
      pytest_args: '--no-cov'  # ignore coverage
      cache_mamba_env: false
      mamba_env_name: ${{ needs.get-date.outputs.DATE }}

  slack-notify-ci:
    needs: test
    uses: arup-group/actions-city-modelling-lab/.github/workflows/slack-notify.yml@main
    secrets: inherit
    with:
      result: needs.test.result
      channel: pam-feed
      message: Daily CI action
