name: Development docs CI

on: 
  push:
    branches:
      - "**"
    paths-ignore:
      - tests/**

defaults:
  run:
    shell: bash -l {0}

permissions:
  contents: write

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # used to build docs into the gh-pages branch without losing branch history. See https://github.com/jimporter/mike/issues/49
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: pam-ubuntu-latest-3.11
        environment-file: requirements/base.txt
        create-args: >-
            -c city-modelling-lab
            -f requirements/dev.txt
            python=3.11
        post-cleanup: all
        cache-environment: true
        
    - name: Setup doc deploy
      run: |
        git config --global user.name Docs deploy
        git config --global user.email docs@dummy.bot.com
    
    - name: Test that docs build
      if: github.ref != 'refs/heads/main'
      run: mike deploy develop

    - name: deploy docs to gh-pages branch
      if: github.ref == 'refs/heads/main'
      run: mike deploy --push develop