name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml
      - ".github/**/*"
      - "!.github/workflows/pr-ci.yml"

jobs:
  lint:
    if: github.event.repository.private
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

  test:
    needs: lint
    if: always() && (needs.lint.result  == 'success' || needs.lint.result  == 'skipped')
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py3version: ["10", "12"]
      fail-fast: false
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@main
    with:
      os: ${{ matrix.os }}
      py3version: ${{ matrix.py3version }}
      notebook_kernel: pam
      lint: false
      pytest_args: '--no-cov'  # ignore coverage
      upload_to_codecov: false

  test-coverage:
    needs: lint
    if: always() && (needs.lint.result  == 'success' || needs.lint.result  == 'skipped')
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@main
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: pam
      lint: false
      pytest_args: 'tests/'  # ignore example notebooks
      upload_to_codecov: ${{ github.event.repository.visibility == 'public' }}  # only attempt to upload if the project is public

  memory-profile:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-memory-profile.yml@main
    with:
      py3version: "12"
      upload_flamegraph: true

  cruft-check:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/template-check.yml@main