name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        py3version: ["9", "10", "11"]
      fail-fast: false
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@bf00346490f8547340c83a58942942bc8458f428
    with:
      os: ${{ matrix.os }}
      py3version: ${{ matrix.py3version }}
      notebook_kernel: pam
      lint: false
      pytest_args: '--no-cov'  # ignore coverage
      upload_to_codecov: false

  test-coverage:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@try-python--m-pytest
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: pam
      lint: false
      pytest_args: 'tests/'  # ignore example notebooks
      upload_to_codecov: true

  memory-profile:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-memory-profile.yml@try-python--m-pytest
    with:
      py3version: "12"
      upload_flamegraph: true