name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-build.yml@main
    secrets: inherit
    with:
      package_name: cml-pam

  pip-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/pip-build.yml@main
    secrets: inherit
    with:
      package_name: cml-pam