name: Release

on:
  release:
    types: [released]

jobs:
  conda-upload:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-upload.yml@main
    secrets: inherit
    with:
      package_name: cml-pam
      build_workflow: pre-release.yml

  pip-upload:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/pip-upload.yml@main
    secrets: inherit
    with:
      package_name: cml-pam
      build_workflow: pre-release.yml

  docs-stable:
    permissions:
      contents: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_stable
      notebook_kernel: pam